### ISSUE TITLE
Add New Assignments

### ISSUE THREAD

**Issue by swarnimstrange** [SAKET-SK/Semester-5-SPPU-Operating-System-Lab#1]
There are several new assignments like Round Robin and SJF CPU scheduling

I can add those if assigned👍

**Comment by SAKET-SK** [comment]
Yeah surely, add the assignments as per the new curriculum. It will be a good lookout practice for assignments for both of us!!👍👍

**Comment by swarnimstrange** [comment]
I added mentioned assignments...your repository was a great help for my OS assignments...Thanks 🙌👍

**Comment by SAKET-SK** [comment]
> I added mentioned assignments...your repository was a great help for my OS assignments...Thanks 🙌👍

Glad to hear. Do visit other repositories in future in case of reference for completion of assignments in upcoming years. Best of Luck 👍
